import type { Metadata } from 'next';

import { ReactNode } from 'react';

import ReactQueryMockProvider from '@/providers/ReactQueryMockProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryMockProvider>{children}</ReactQueryMockProvider>
      </body>
    </html>
  );
}
